apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpZHBkZXZlYWNyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJpZHBkZXZlYWNyIiwicGFzc3dvcmQiOiJBWlNINktXKy91VHNSUk8yWWxzMU9FSkdHM3IzYXpVblhwWTNBekV2dWIrQUNSQ0ZwTGxoIiwiYXV0aCI6ImFXUndaR1YyWldGamNqcEJXbE5JTmt0WEt5OTFWSE5TVWs4eVdXeHpNVTlGU2tkSE0zSXpZWHBWYmxod1dUTkJla1YyZFdJclFVTlNRMFp3VEd4byJ9fX0=
kind: Secret
metadata:
  name: registry-auth
  namespace: demo
type: kubernetes.io/dockerconfigjson
