apiVersion: apps/v1
kind: Deployment
metadata:
  name: demap1
  namespace: demo
  labels:
<<<<<<< HEAD
    #tekton.dev/pipelines: default/springboot-pipeline
=======
    #tekton.dev/pipelines: demo/springboot-pipeline
>>>>>>> 5b23e914d61ee7784fd1659906fbf3797276b8ca
    'backstage.io/kubernetes-id': 'demap1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demap1
  template:
    metadata:
      labels:
        app: demap1
        'backstage.io/kubernetes-id': 'demap1'
    spec:
<<<<<<< HEAD
      imagePullSecrets:
      - name: registry-auth
      containers:
        - name: demap1
          image: idpdeveacr.azurecr.io/pet-clinic:latest
=======
      containers:
        - name: demap1
          image: backstagdeveacr.azurecr.io/demap1:latest
>>>>>>> 5b23e914d61ee7784fd1659906fbf3797276b8ca
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demap1
  namespace: demo
spec:
  selector:
    app: demap1
  ports:
    - name: http
      port: 80
      targetPort: 8080
<<<<<<< HEAD
  type: NodePort
=======
  type: NodePort
>>>>>>> 5b23e914d61ee7784fd1659906fbf3797276b8ca
