apiVersion: apps/v1
kind: Deployment
metadata:
  name: demap1
  namespace: demo
  labels:
    #tekton.dev/pipelines: demo/springboot-pipeline
    'backstage.io/kubernetes-id': 'demap1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demap1
  template:
    metadata:
      labels:
        app: demap1
        'backstage.io/kubernetes-id': 'demap1'
    spec:
      containers:
        - name: demap1
          image: backstagdeveacr.azurecr.io/demap1:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demap1
  namespace: demo
spec:
  selector:
    app: demap1
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort